// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: tlc/tlc.proto

package tlc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Dirs          []*Dir                 `protobuf:"bytes,2,rep,name=dirs,proto3" json:"dirs,omitempty"`
	Symlinks      []*Symlink             `protobuf:"bytes,3,rep,name=symlinks,proto3" json:"symlinks,omitempty"`
	Size          int64                  `protobuf:"varint,16,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_tlc_tlc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_tlc_tlc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_tlc_tlc_proto_rawDescGZIP(), []int{0}
}

func (x *Container) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Container) GetDirs() []*Dir {
	if x != nil {
		return x.Dirs
	}
	return nil
}

func (x *Container) GetSymlinks() []*Symlink {
	if x != nil {
		return x.Symlinks
	}
	return nil
}

func (x *Container) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Dir struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dir) Reset() {
	*x = Dir{}
	mi := &file_tlc_tlc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dir) ProtoMessage() {}

func (x *Dir) ProtoReflect() protoreflect.Message {
	mi := &file_tlc_tlc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dir.ProtoReflect.Descriptor instead.
func (*Dir) Descriptor() ([]byte, []int) {
	return file_tlc_tlc_proto_rawDescGZIP(), []int{1}
}

func (x *Dir) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Dir) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_tlc_tlc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_tlc_tlc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_tlc_tlc_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Symlink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Dest          string                 `protobuf:"bytes,3,opt,name=dest,proto3" json:"dest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Symlink) Reset() {
	*x = Symlink{}
	mi := &file_tlc_tlc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symlink) ProtoMessage() {}

func (x *Symlink) ProtoReflect() protoreflect.Message {
	mi := &file_tlc_tlc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symlink.ProtoReflect.Descriptor instead.
func (*Symlink) Descriptor() ([]byte, []int) {
	return file_tlc_tlc_proto_rawDescGZIP(), []int{3}
}

func (x *Symlink) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Symlink) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Symlink) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

var File_tlc_tlc_proto protoreflect.FileDescriptor

const file_tlc_tlc_proto_rawDesc = "" +
	"\n" +
	"\rtlc/tlc.proto\x12\x11io.itch.wharf.tlc\"\xb2\x01\n" +
	"\tContainer\x12-\n" +
	"\x05files\x18\x01 \x03(\v2\x17.io.itch.wharf.tlc.FileR\x05files\x12*\n" +
	"\x04dirs\x18\x02 \x03(\v2\x16.io.itch.wharf.tlc.DirR\x04dirs\x126\n" +
	"\bsymlinks\x18\x03 \x03(\v2\x1a.io.itch.wharf.tlc.SymlinkR\bsymlinks\x12\x12\n" +
	"\x04size\x18\x10 \x01(\x03R\x04size\"-\n" +
	"\x03Dir\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\"Z\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\"E\n" +
	"\aSymlink\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x12\n" +
	"\x04dest\x18\x03 \x01(\tR\x04destB\x1cZ\x1agithub.com/itchio/lake/tlcb\x06proto3"

var (
	file_tlc_tlc_proto_rawDescOnce sync.Once
	file_tlc_tlc_proto_rawDescData []byte
)

func file_tlc_tlc_proto_rawDescGZIP() []byte {
	file_tlc_tlc_proto_rawDescOnce.Do(func() {
		file_tlc_tlc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tlc_tlc_proto_rawDesc), len(file_tlc_tlc_proto_rawDesc)))
	})
	return file_tlc_tlc_proto_rawDescData
}

var file_tlc_tlc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tlc_tlc_proto_goTypes = []any{
	(*Container)(nil), // 0: io.itch.wharf.tlc.Container
	(*Dir)(nil),       // 1: io.itch.wharf.tlc.Dir
	(*File)(nil),      // 2: io.itch.wharf.tlc.File
	(*Symlink)(nil),   // 3: io.itch.wharf.tlc.Symlink
}
var file_tlc_tlc_proto_depIdxs = []int32{
	2, // 0: io.itch.wharf.tlc.Container.files:type_name -> io.itch.wharf.tlc.File
	1, // 1: io.itch.wharf.tlc.Container.dirs:type_name -> io.itch.wharf.tlc.Dir
	3, // 2: io.itch.wharf.tlc.Container.symlinks:type_name -> io.itch.wharf.tlc.Symlink
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tlc_tlc_proto_init() }
func file_tlc_tlc_proto_init() {
	if File_tlc_tlc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tlc_tlc_proto_rawDesc), len(file_tlc_tlc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tlc_tlc_proto_goTypes,
		DependencyIndexes: file_tlc_tlc_proto_depIdxs,
		MessageInfos:      file_tlc_tlc_proto_msgTypes,
	}.Build()
	File_tlc_tlc_proto = out.File
	file_tlc_tlc_proto_goTypes = nil
	file_tlc_tlc_proto_depIdxs = nil
}
